<NODE name="Settings">
    <ExperimentSettings measurement_count="i:0" overload_rejecion="bool:False" load_resistance="i:99" homemade_amp_coeff="i:178" averages="i:100" meas_characteristic_type="i:0" name="ExperimentSettings" working_directory="C:/Users/i.zadorozhnyi/Desktop" use_set_vds_range="bool:True" use_homemade_amplifier="bool:True" display_refresh="i:10" measurement_name="" transistor_list="" calibrate_before_measurement="bool:False" use_automated_voltage_control="bool:True" use_second_amplifier="bool:True" use_set_vfg_range="bool:True" meas_gated_structure="bool:True" drain_source_voltage="f:0.0" front_gate_voltage="i:0" need_measure_temperature="bool:False" experiment_name="fsafasf" second_amp_coeff="i:100" use_transistor_selector="bool:False">
        <ValueRange points="i:10" start_value="i:0" end_value="i:1" end_units="i:0" start_units="i:0" range_mode="i:0" name="drain_source_range"/>
        <ValueRange points="i:10" start_value="i:0" end_value="i:1" end_units="i:0" start_units="i:0" range_mode="i:0" name="front_gate_range"/>
    </ExperimentSettings>
    <HardwareSettings dsa_resource="GPIB0::6::INSTR" sample_multimeter_resource="GPIB0::23::INSTR" arduino_controller_resource="COM27" sample_potentiometer_channel="i:0" gate_potentiometer_channel="i:1" main_gate_multimeter_resource="GPIB0::22::INSTR" name="HardwareSettings"/>
</NODE>
