<NODE name="Settings">
    <ExperimentSettings use_second_amplifier="bool:True" working_directory="" display_refresh="i:10" averages="i:100" use_transistor_selector="bool:False" second_amp_coeff="i:100" use_set_vds_range="bool:False" calibrate_before_measurement="bool:False" measurement_count="i:0" transistor_list="" use_set_vfg_range="bool:False" name="ExperimentSettings" overload_rejecion="bool:False" meas_gated_structure="bool:True" load_resistance="i:5000" need_measure_temperature="bool:False" homemade_amp_coeff="i:178" drain_source_voltage="i:0" use_homemade_amplifier="bool:True" front_gate_voltage="i:0" measurement_name="" meas_characteristic_type="i:0" experiment_name="">
        <ValueRange start_units="i:0" end_units="i:0" points="i:10" end_value="i:1" start_value="i:0" name="drain_source_range" range_mode="i:0"/>
        <ValueRange start_units="i:0" end_units="i:0" points="i:10" end_value="i:1" start_value="i:0" name="front_gate_range" range_mode="i:0"/>
    </ExperimentSettings>
    <HardwareSettings arduino_controller_resource="" sample_potentiometer_channel="i:0" sample_multimeter_resource="" dsa_resource="" name="HardwareSettings" gate_potentiometer_channel="i:0" main_gate_multimeter_resource=""/>
</NODE>
