<NODE name="Settings">
    <ExperimentSettings need_measure_temperature="bool:False" front_gate_voltage="i:0" use_second_amplifier="bool:True" averages="i:100" second_amp_coeff="i:100" meas_gated_structure="bool:True" load_resistance="i:5000" use_transistor_selector="bool:False" working_directory="" measurement_name="" transistor_list="" drain_source_voltage="i:0" measurement_count="i:0" homemade_amp_coeff="i:178" experiment_name="hggccfvfvggbghnh" use_set_vds_range="bool:False" overload_rejecion="bool:False" name="ExperimentSettings" display_refresh="i:10" meas_characteristic_type="i:0" calibrate_before_measurement="bool:False" use_homemade_amplifier="bool:True" use_set_vfg_range="bool:False">
        <ValueRange end_value="i:1" start_units="i:0" name="drain_source_range" range_mode="i:0" start_value="i:0" points="i:10" end_units="i:0"/>
        <ValueRange end_value="i:1" start_units="i:0" name="front_gate_range" range_mode="i:0" start_value="i:0" points="i:10" end_units="i:0"/>
    </ExperimentSettings>
    <HardwareSettings dsa_resource="" main_gate_multimeter_resource="" gate_potentiometer_channel="i:0" arduino_controller_resource="" name="HardwareSettings" sample_multimeter_resource="" sample_potentiometer_channel="i:0"/>
</NODE>
